pipeline {
    agent any
    tools { 
        nodejs "nodejs" 
    }    
    environment {
        imageName = "programwithnavas/react-app"
        registryCredentials = "mohammednavasdocker"
        dockerImage = ""
    }
    stages {
        stage('Clean up'){
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo'){
            steps {
                sh 'git clone https://github.com/Mohammed-NavasKhan/jenkins-docker-react.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('jenkins-docker-react/React') {
                    sh 'npm install'
                }
            }
        }
        stage('Unit Tests') {
            steps {
                dir('jenkins-docker-react/React') {
                    sh 'npm run test'
                }
            }
        }
        stage('Building Image') {
            steps {  
                dir('jenkins-docker-react/React') {        
                    script {
                        dockerImage = docker.build imageName
                    }
                }                 
            }   
        }
        stage('Deploying Image') {
            steps {  
                script {
                    docker.withRegistry("https://registry.hub.docker.com", "dockerhub-cred"){
                        dockerImage.push("${env.BUILD_NUMBER}")
                    }
                }
            }   
        }

    }
}
