# we will use node:alpine docker image
FROM node:20.9.0-alpine3.18 AS base

# set /app as work directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package*.json /.

# install npm dependencies
RUN npm install 

# copy your project files to work directory
COPY . .

# run your app
CMD ["npm", "start"] # OR CMD ['yarn', 'run', 'start']