worker_processes 4;

events {
    worker_connections 1024;
}
http {
    include mime.types;

    log_format main '$http_x_forwarded_for - $http_referer - [$time_local] "$request" "$request_body" $status $body_bytes_sent';

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_min_length 0;
    gzip_types text/plain application/javascript text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/vnd.ms-fontobject application/x-font-ttf font/opentype;

    server {
        listen 3010;
        access_log /var/log/nginx/access.log;

        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location ~ \.(jpg|jpeg|png|gif|ico|woff|woff2|ttf|svg)$ {
            root /usr/share/nginx/html;
            expires 1h;
            add_header Cache-Control "no-store";
            add_header Cache-Control max-age=120;
        }

        error_page 500 502 503 504 /50x.html;

        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}