pipeline {
    agent any
    tools { 
        nodejs "nodejs" 
    }    
    environment {
        imageName = "mohammednavasdocker/react-docker-w-nginx"
        registryCredentials = "mohammednavasdocker"
        dockerImage = ""
    }
    stages {
        stage('Clean up'){
            steps {
                deleteDir()
            }
        }
        stage('Clone Repo'){
            steps {
                sh 'git clone https://github.com/Mohammed-NavasKhan/jenkins-docker-react.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                dir('jenkins-docker-react/react-docker-w-nginx') {
                    sh "npm cache clear --force"
                    sh 'npm install'
                }
            }
        }
        stage('Building Image') {
            steps {  
                dir('jenkins-docker-react/react-docker-w-nginx') {        
                    script {
                        dockerImage = docker.build imageName
                    }
                }                 
            }   
        }
        stage('Archive Docker Image') {
            steps {
                archiveArtifacts artifacts: imageName, allowEmptyArchive: true
            }
        }
        stage('Deploying Image') {
            steps {  
                script {
                    docker.withRegistry("https://registry.hub.docker.com", "dockerhub-creds"){
                        dockerImage.push("${env.BUILD_NUMBER}")
                    }
                }
            }   
        }

    }
}
